{ Help Contexts - (c) 1994 SSG }

unit WHelp;

interface

const

  hcNOCONTEXT= 0;
  hcCONTENTS= 1;
  hcFILTERS= 2;
  hcFILTERDK= 3;
  hcGLOBAL= 4;
  hcDESQVIEW= 5;
  hcCMDLINE= 6;
  hcDOS= 7;
  hcWINDOWS= 8;
  hcOS2= 9;
  hcKEYMASK= 10;
  hcEMAIL= 11;
  hcSETUPDIALOG= 12;
  hcPACKETOPENDIALOG= 13;
  hcILLEGALSETUP= 14;
  hcHELPONHELP= 15;
  hcABOUT= 16;
  hcAREALISTWINDOW= 17;
  hcMSGWINDOW= 18;
  hcEXECERROR= 19;
  hcOUTOFMEM= 20;
  hcFILEERROR= 21;
  hcTAGLINESELECTDIALOG= 22;
  hcMANUALENTRY= 23;
  hcNOWRITE= 24;
  hcAREACHANGE= 25;
  hcREPLYLISTWINDOW= 26;
  hcPRINTERSETUP= 27;
  hcREPLYWINDOW= 28;
  hcNEWPACKET= 29;
  hcUNREADDIALOG= 30;
  hcBENEFITS= 31;
  hcREGISTRATION= 32;
  hcTAGLINEINPUTDIALOG= 33;
  hcASKPOST= 34;
  hcMMA= 35;
  hcTAGLINEMANAGERDIALOG= 36;
  hcMENUWINDOW= 37;
  hcPERSONDIALOG= 38;
  hcPERSONNOTFOUND= 39;
  hcUUDECODEPROMPT= 40;
  hcNETFLAGCHANGEDIALOG= 41;
  hcTEXTSEARCHDIALOG= 42;
  hcALARMSETUPDIALOG= 43;
  hcPARAMINPUTDIALOG= 44;
  hcFILEVIEWOPENDIALOG= 45;
  hcNODLAREAWARN= 46;
  hcNOOLCSUPPORT= 47;
  hcREPLYPACKETCONFLICT= 48;
  hcMULTIUSEREXAMPLES= 49;
  hcSAVEMSGINVALIDNAME= 50;
  hcCOLORCONFIGDIALOG= 51;
  hcARCHIVERSETUPDIALOG= 52;
  hcFILTERLOOKUP= 53;
  hcVIVALASEWAGE= 54;
  hcSEARCHDIALOG= 55;
  hcTAGLINEIMPORTHELP= 56;
  hcCATEGORYADD= 57;
  hcCATEGORYEDIT= 58;
  hcTAGLINECATEGORIES= 59;
  hcFILTERINSTALL= 60;

implementation

end.
